<?php

namespace App\Http\Requests\Quote;

use App\Rules\PhoneNumber;
use Illuminate\Foundation\Http\FormRequest;

class ApiQuoteCustomerUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth()->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'quote_id' => 'required',
            'shipping_name' => 'required',
            'shipping_city_id' => 'required',
            'shipping_district_id' => 'required',
            'shipping_ward_id' => 'sometimes',
            'shipping_address' => 'required',
            'shipping_phone' => ['required', 'numeric', new PhoneNumber],
            'comment' => 'sometimes',
            'payment_method_id' => 'required',
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array
     */
    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }
}
